version: '3.6'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: empose
      POSTGRES_USER: empose
      POSTGRES_PASSWORD: emp123
  web:
    image: nginx
    volumes:
      - ./share:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 4200:80
    expose:
      - 4200
      # - 0.0.0.0:4200:80
    # network_mode: bridge
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


#http://localhost:8080/?pgsql=db&username=empose&db=empose&ns=public